import type { Metadata } from 'next';
import Footer from './section/Footer';
import Navbar from './component/Navbar';
import "./globals.css";
import { Montserrat } from "next/font/google";


export const metadata : Metadata = {
  title: "Site And Lifestyle",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight >>> https://fonts.google.com/variablefonts
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return(
    <html lang="en">
      <body>
       <main>
           
            <main className="relative overflow-hidden">
              <section className="padding-x bg-[#0F372F]">
              <Navbar/>
              </section>   
            {children}
        <section className="padding-x sm:bg-[#0F372F] sm:text-white bg-white">
        <Footer/>
       </section>
            </main>
        
          </main>
      </body>
    </html>
  )
}
